// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2G6k6iI78k7Z2dbr-_kh655sPUZ5E0BQ',
    appId: '1:757109925372:web:728fa4606b53707cb83e79',
    messagingSenderId: '757109925372',
    projectId: 'ecommerceappflutter-9c8da',
    authDomain: 'ecommerceappflutter-9c8da.firebaseapp.com',
    storageBucket: 'ecommerceappflutter-9c8da.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpp_zmuWDDgsBFa6wi7g93R908pPdWbWI',
    appId: '1:757109925372:android:3a5fe87aad05a2dbb83e79',
    messagingSenderId: '757109925372',
    projectId: 'ecommerceappflutter-9c8da',
    storageBucket: 'ecommerceappflutter-9c8da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJFQ9tB5ouElAFD85selVEUG_SmTRoOhw',
    appId: '1:757109925372:ios:06fe6e47594feac2b83e79',
    messagingSenderId: '757109925372',
    projectId: 'ecommerceappflutter-9c8da',
    storageBucket: 'ecommerceappflutter-9c8da.firebasestorage.app',
    androidClientId: '757109925372-ceinqr8gfnb0ldjuo95c40s8agbn12d8.apps.googleusercontent.com',
    iosClientId: '757109925372-tj4v9c9nthbrp5n1ks7b469re2s06kmg.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommereceFlutterApp',
  );

}